// src/types.ts

export type RenderShieldSeverity =
  | "Stable"
  | "Changed (non-UI key)"
  | "Changed (watched key)"
  | "Custom compare triggered";

/** @deprecated Use RenderShieldSeverity. Kept for backward compatibility. */
export type DiffSeverity = RenderShieldSeverity;

export type RenderShieldDiff = {
  componentName?: string;
  shielded: boolean;
  renderCount: number;
  changedKeys: string[];
  stableKeys: string[];
  watchedChanged: string[];
  watchedStable: string[];
  severity: RenderShieldSeverity;

  /**
   * v0.3.0
   * Enables the dev HUD toast for this report event.
   * Set by hook/HOC from RenderShieldOptions.visual.
   */
  visual?: boolean;

  /**
   * Recommendations generated by report.ts based on pattern analysis.
   * Only present when patterns are detected (low-noise).
   */
  recommendations?: string[];

  /**
   * Component contract definition (what paths matter for this component).
   * Passed through from RenderShieldOptions.contract.
   */
  contract?: {
    watch: string[];
    description?: string;
  };
};

export type RenderShieldOptions<T> = {
  watch?: string[];
  debug?: boolean;

  /**
   * v0.3.0
   * When true, render shielded events will show a small dev HUD toast.
   */
  visual?: boolean;

  /**
   * When false, diagnostics are reported but the hook always returns the current value
   * (no shielding behavior). Enables safe experimentation: see what would happen without
   * changing component behavior. Default: true (backward compatible).
   */
  shield?: boolean;

  /**
   * Component contract: documents which paths matter for this component.
   * Used for contract compliance reporting and recommendations.
   */
  contract?: {
    watch: string[];
    description?: string;
  };

  /**
   * Custom equality comparator. Same contract as React.memo:
   * return `true` when prev and next are considered equal (shield / prevent rerender).
   */
  customCompare?: (prev: T, next: T) => boolean;

  /**
   * Optional explicit name for hook-based usage (HOC derives name automatically).
   */
  componentName?: string;
};
